[package]
name = "irongolem"
version = "0.1.0"
description = "Graph Optimiser for Learning and Evolution of Models"

authors = ["Georgii Lopatenko <lopa10ko@itmo.ru>"]
readme = "../../README.md"
license = "BSD-3-Clause"
edition = "2021"
repository = "https://github.com/Lopa10ko/irongolem"
rust-version = "1.78"
keywords = ["optimization", "graphs", "evolutionary"]
categories = ["science", "algorithms"]

[lib]
path = "src/lib.rs"
